#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.62
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config border_width 0
bspc config focus_follows_pointer true

#feh --bg-fill $HOME/Downloads/blue-sky/wallpapers/blue3.png
~/.screenlayout/turn-off-secondary-display-2.sh
xsetroot -cursor_name left_ptr &
nitrogen --restore
~/.config/polybar/launch.sh
picom &
#picom --experimental-backends &
